# Test your FastAPI endpoints

POST http://localhost:8000/answers/
Content-Type: application/json

[
           {
             "user_answered": 2,
             "user_reviewed": 1,
             "answer_text": "Great performance",
             "question_text": "How would you rate their performance?"
           },
           {
             "user_answered": 3,
             "user_reviewed": 1,
             "answer_text": "Very good",
             "question_text": "How would you rate their performance?"
           }
         ]

###

GET http://localhost:8000/test

