version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: ./front  # Путь к директории с Dockerfile для Vue.js
      dockerfile: Dockerfile
    ports:
      - "8080:5173"


