# Generated by Django 3.2.25 on 2024-11-02 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Methodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('criteria', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('full_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('department', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('male', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StatusMethodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('methodology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.methodology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ResultMethodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix_competence', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('methodology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.methodology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField()),
                ('methodology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.methodology')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.userprofile')),
            ],
        ),
    ]
