# Generated by Django 3.2.25 on 2024-11-04 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('methodology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.methodology')),
                ('user_accept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_user_accepted', to='forms.userprofile')),
                ('user_given', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_user_given', to='forms.userprofile')),
            ],
        ),
    ]
